cartesian_vel_controller:
  ros__parameters:
    type: tsid_controllers/CartesianVelocityController
    
    joint_state_names:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint

    joint_command_names:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint

    interface_name: position

    ee_names:
      - arm_right_7_link

    velocity_scaling: 1.0

    posture_gain: 1.0

    cartesian_vel_gain:
         arm_right_7_link:
          kp_x: 250.0
          kp_y: 250.0
          kp_z: 250.0
          kp_roll: 250.0
          kp_pitch: 250.0
          kp_yaw: 250.0
          ki_x: 5.0
          ki_y: 5.0
          ki_z: 5.0
          ki_roll: 5.0
          ki_pitch: 5.0
          ki_yaw: 5.0
          kd_x: 0.05
          kd_y: 0.05
          kd_z: 0.05
          kd_roll: 0.05
          kd_pitch: 0.05
          kd_yaw: 0.05




