cartesian_space_controller:
  ros__parameters:
    type: tsid_controllers/CartesianSpaceController
    update_rate: 25
  
    local_frame: false
     
    joint_state_names:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
      - torso_lift_joint

    joint_command_names:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint

    interface_name: position

    ee_names:
      - arm_right_7_link

    ee_vmax: 0.15

    velocity_scaling: 1.0

    joint_pos_gain:
    #Real robot values
      arm_right_1_joint:
        kp: 100.0
        kd: 15.0
      arm_right_2_joint:
        kp: 100.0
        kd: 15.0
      arm_right_3_joint:
        kp: 100.0
        kd: 15.0
      arm_right_4_joint:
        kp: 100.0
        kd: 15.0
      arm_right_5_joint:
        kp: 200.0
        kd: 7.50
      arm_right_6_joint:
        kp: 200.0
        kd: 7.50
      arm_right_7_joint:
        kp: 50.0
        kd: 0.2
    #Simulation
      #arm_right_1_joint:
      #  kp: 100.0
      #  kd: 50.0
      #arm_right_2_joint:
      #  kp: 100.0
      #  kd: 50.0
      #arm_right_3_joint:
      #  kp: 100.0
      #  kd: 50.0
      #arm_right_4_joint:
      #  kp: 100.0
      #  kd: 50.0
      #arm_right_5_joint:
      #  kp: 100.0
      #  kd: 50.0
      #arm_right_6_joint:
      #  kp: 100.0
      #  kd: 50.0
      #arm_right_7_joint:
      #  kp: 100.0
      #  kd: 50.0

    cartesian_gain:
         arm_right_7_link:
          #kp_x: 1500.0
          #kp_y: 1500.0
          #kp_z: 1500.0
          #kp_roll: 700.0
          #kp_pitch: 700.0
          #kp_yaw: 700.0
          kp_x: 500.0
          kp_y: 500.0
          kp_z: 1000.0
          kp_roll: 70.0
          kp_pitch: 70.0
          kp_yaw: 70.0

