cartesian_space_controller:
  ros__parameters:
    type: tsid_controllers/CartesianSpaceController
    update_rate: 25
  
    local_frame: false
     
    joint_state_names:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint

    joint_command_names:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint


    interface_name: position

    ee_names:
      - arm_right_7_link

    ee_vmax: 0.15

    velocity_scaling: 1.0

    joint_pos_gain:
    #Real robot values
      arm_right_1_joint:
        kp: 25.0
        kd: 110.0
      arm_right_2_joint:
        kp: 25.0
        kd: 110.0
      arm_right_3_joint:
        kp: 25.0
        kd: 110.0
      arm_right_4_joint:
        kp: 25.0
        kd: 110.0
      arm_right_5_joint:
        kp: 25.0
        kd: 110.0
      arm_right_6_joint:
        kp: 25.0
        kd: 110.0
      arm_right_7_joint:
        kp: 25.0
        kd: 110.0
    #Simulation
      #arm_right_1_joint:
      #  kp: 100.0
      #  kd: 50.0
      #arm_right_2_joint:
      #  kp: 100.0
      #  kd: 50.0
      #arm_right_3_joint:
      #  kp: 100.0
      #  kd: 50.0
      #arm_right_4_joint:
      #  kp: 100.0
      #  kd: 50.0
      #arm_right_5_joint:
      #  kp: 100.0
      #  kd: 50.0
      #arm_right_6_joint:
      #  kp: 100.0
      #  kd: 50.0
      #arm_right_7_joint:
      #  kp: 100.0
      #  kd: 50.0

    cartesian_gain:
         arm_right_7_link:
          kp_x: 300.0
          kp_y: 300.0
          kp_z: 300.0
          kp_roll: 100.0
          kp_pitch: 100.0
          kp_yaw: 100.0
          #kp_x: 200.0
          #kp_y: 200.0
          #kp_z: 200.0
          #kp_roll: 70.0
          #kp_pitch: 70.0
          #kp_yaw: 70.0
          kd_x: 2100.0
          kd_y: 2100.0
          kd_z: 2100.0
          kd_roll: 500.0
          kd_pitch: 500.0
          kd_yaw: 500.0
          

