joint_space_vel_controller:
  ros__parameters:
    type: tsid_controllers/JointSpaceVelTsidController
    update_rate: 1000
    
    joint_state_names:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint


    joint_command_names:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint

    interface_name: position

    joint_vel_gain:
      arm_right_1_joint:
        kp: 50.0
        kd: 0.2
        ki: 0.05
      arm_right_2_joint:
        kp: 50.0
        kd: 0.2
        ki: 0.05
      arm_right_3_joint:
        kp: 50.0
        kd: 0.2
        ki: 0.05
      arm_right_4_joint:
        kp: 50.0
        kd: 0.2
        ki: 0.05
      arm_right_5_joint:
        kp: 50.0
        kd: 0.2
        ki: 0.05
      arm_right_6_joint:
        kp: 50.0
        kd: 0.2
        ki: 0.05
      arm_right_7_joint:
        kp: 50.0
        kd: 0.2
        ki: 0.05
    

    velocity_scaling: 1.0
    posture_gain: 100.0

