joint_space_controller:
  ros__parameters:
    type: tsid_controllers/JointSpaceTsidController
    update_rate: 1000
    
    joint_state_names:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint

    joint_command_names:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint

    interface_name: position

    velocity_scaling: 1.0

    joint_pos_gain:
    #Real robot values
      #arm_right_1_joint:
      #  kp: 25000.0
      #  kd: 850.0
      #arm_right_2_joint:
      #  kp: 25000.0
      #  kd: 850.0
      #arm_right_3_joint:
      #  kp: 40000.0
      #  kd: 1000.0
      #arm_right_4_joint:
      #  kp: 40000.0
      #  kd: 1000.0
      #arm_right_5_joint:
      #  kp: 20000.0
      #  kd: 1000.0
      #arm_right_6_joint:
      #  kp: 15000.0
      #  kd: 1000.0
      #arm_right_7_joint:
      #  kp: 50.0
      #  kd: 0.2
    #Simulation
      arm_right_1_joint:
        kp: 100.0
        kd: 50.0
      arm_right_2_joint:
        kp: 100.0
        kd: 50.0
      arm_right_3_joint:
        kp: 100.0
        kd: 50.0
      arm_right_4_joint:
        kp: 100.0
        kd: 50.0
      arm_right_5_joint:
        kp: 100.0
        kd: 50.0
      arm_right_6_joint:
        kp: 100.0
        kd: 50.0
      arm_right_7_joint:
        kp: 100.0
        kd: 50.0
    
