joint_space_controller:
  ros__parameters:
    type: tsid_controllers/JointSpaceTsidController
    update_rate: 25
    
    joint_names:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint

    interface_name: position

    velocity_scaling: 1.0
    posture_gain: 100.0

