dynamic_tsid_controller:
  ros__parameters:
    type: dynamic_tsid_controller/DynamicTsidController
    joint_names:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint

    interface_name: position

    ee_names:
      - arm_right_7_link

    velocity_scaling: 0.2


    cartesian_gain:
        arm_right_7_link:
          kp_x: 1000.0
          kp_y: 1000.0
          kp_z: 1500.0
          kp_roll: 500.0
          kp_pitch: 500.0
          kp_yaw: 500.0
    

