dynamic_tsid_controller:
  ros__parameters:
    type: dynamic_tsid_controller/DynamicTsidController
    joint_names:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
    interface_name: position

    ee_names:
      - arm_right_7_link
      - arm_left_7_link
    

